Let's see if this does the job as good as my self-made scripts ;) First fix: let it find kde-buildrc even if called as kdesdk/scripts/kde-build
svn path=/trunk/kdesdk/scripts/; revision=160487

diff --git a/kde-build b/kde-build
--- a/kde-build
+++ b/kde-build
@@ -170,10 +170,12 @@ fi
 # Get current configuration, bail out if it couldn't be found.
 #
 if !(test -e ./kde-buildrc); then
-  echo "ERROR: Cannot load configuration file ./kde-buildrc!"; exit $err_no_config
-else
-  . ./kde-buildrc
+  cd `dirname $0`
+  if !(test -e ./kde-buildrc); then
+    echo "ERROR: Cannot load configuration file ./kde-buildrc!"; exit $err_no_config
+  fi
 fi
+. ./kde-buildrc
 
 if test -z "$MAKE"; then
   MAKE=make
