support OBJ_SUBDIR: if you have the builddir as subdir of the srcdir, you can just set OBJ_SUBDIR to the directory name and can use makeobj witout any sed tricks
svn path=/trunk/kdesdk/scripts/; revision=119458

diff --git a/makeobj b/makeobj
--- a/makeobj
+++ b/makeobj
@@ -29,11 +29,31 @@ while test $# -gt 0 ; do
 done
 
 if test ! -f $dir/$file; then
-  pwd=`echo $PWD | sed -e $OBJ_REPLACEMENT`
-  if test ! -f $pwd/$dir/$file; then
-  	echo "no objdir found"
+  if test -n "$OBJ_REPLACEMENT"; then
+    pwd=`echo $PWD | sed -e "$OBJ_REPLACEMENT"`
+    if test ! -f $pwd/$dir/$file; then
+  	 echo "no objdir found. Tried $pwd"
+	 exit 1
+    fi
+    cd $pwd/$dir
+  else
+    if test -n "$OBJ_SUBDIR"; then
+       dir=$PWD
+       subdir=.
+       while test ! -f $dir/$OBJ_SUBDIR/$file; do
+	 subdir=`basename $dir`"/$subdir"
+	 dir=`dirname $dir`
+	 if test "$dir" = "/"; then
+	    # the case that someone puts the compile dir in /
+	    # is very unlikely, so we better skip here ;)
+	    echo "can't find $OBJ_SUBDIR above current dir"
+	    exit 1
+	 fi
+       done
+       cd $dir/$OBJ_SUBDIR/$subdir
+
+    fi
   fi
-  cd $pwd/$dir
 else
   cd $dir
 fi
