Improved version of the svn-clean script, with inputs from coolo & dfaure
svn path=/trunk/KDE/kdesdk/scripts/; revision=413252

diff --git a/svn-clean b/svn-clean
--- a/svn-clean
+++ b/svn-clean
@@ -17,8 +17,31 @@
 # This script processes the output from the SVN executable
 # Do not run it along with colorsvn
 
+version="svn-clean v0.2"
+heading="$version: cleans up the Subversion working directory"
+
 SVN=`type -p svn`
 RM=/bin/rm
+force=false
+quiet=false
+
+function check_confirm() {
+  if $force; then
+    return
+  fi
+  
+  echo "This will erase files and directories that aren't in Subversion"
+  echo -n "Are you sure you want to continue? (y/n) "
+  
+  read answer < /dev/tty
+  if echo "$answer" | grep -q "^[Yy]"; then
+    force=true
+    return
+  fi
+  
+  # user cancelled
+  exit 0
+}
 
 if [ -z "$SVN" ]; then
     echo "Subversion executable (svn) not found" >&2
@@ -34,26 +57,66 @@ if [ \! -x "$SVN" ]; then
     exit 1
 fi
 
-# Parse -n argument: dry-run
-if [ "$1" = "-n" ]; then
-    RM=/bin/true
-    shift
-fi
+# Parse arguments
+while [ $# -gt 0 ]; do
+  case "$1" in
+    -n)
+      RM=/bin/true
+      force=true
+      ;;
+    -f)
+      force=true
+      ;;
+    -i)
+      force=false
+      ;;
+    -q)
+      quiet=true
+      ;;
+    -h)
+      cat <<EOF
+$heading
+svn-clean [-h] [-n] [-q] [-i|-f] [dirname]
+
+Where:
+  -h      shows this help screen
+  -n      dry-run: doesn't actually erase the files, just show their names
+  -i      interactive: ask for confirmation before erasing the files
+  -f      force: doesn't ask for confirmation before erasing
+  -q      quiet: doesn't show output
+EOF
+      exit 0
+      ;;
+    -*)
+      echo "Invalid option $1" >&2
+      ;;
+    *)
+      break
+      ;;
+  esac
+  shift
+done
 
 # Unset TERM just so that no colours are output
 # in case $SVN points to colorsvn
 unset TERM
 
-$SVN status --no-ignore | grep '^[I?]' | cut -b8- | \
-    while read file; do
+$quiet || cat <<EOF
+$heading
+
+EOF
+
+$SVN status --no-ignore "$1" | grep '^[I?]' | cut -b8- | \
+  while read file; do
+    check_confirm
     if [ -f $file -o -L $file ]; then
-	echo "F $file"
+	$quiet || echo "F $file"
 	$RM $file
     elif [ -d $file ]; then
-	echo "D $file"
+	$quiet || echo "D $file"
 	$RM -r $file
     else
-	echo "? $file"
+	$quiet || echo "? $file"
 	$RM -r $file
     fi
 done
